[project]
name = "adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-adk>=1.19.0",
    "google-generativeai>=0.8.5",
    "greenlet>=3.2.4",
    "litellm==1.80.5",
    "yfinance>=0.2.66",
]
